language: php
php:
 - '7.2'

install:
  - travis_retry docker-compose exec test composer install --no-interaction

before_script:
  - export CODECOV_TOKEN="6de43b13-9ea8-498c-bb32-c29f3f098517"

script: vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
