language: php
php:
 - '7.2'
 - '7.3'

env:
 matrix:
  - LARAVEL='^6.0'
  - LARAVEL='^7.0'
  - LARAVEL='^8.0'

jobs:
 exclude:
  - php: '7.2'
    env: LARAVEL='^8.0'

install:
 - travis_retry composer require "illuminate/database:${LARAVEL}" --no-update
 - travis_retry composer install --prefer-source --no-interaction

before_script:
  - export CODECOV_TOKEN="6de43b13-9ea8-498c-bb32-c29f3f098517"

script: vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
